### ISSUE TITLE
Blog SEO

### ISSUE THREAD

**Issue by mavsan** [suresoftware/october-power-seo#1]
Do not work with the blog.

**Comment by Humni** [comment]
I have this working with the blog on multiple live sites. Can you provide
more details?

**Comment by mavsan** [comment]
I add {% component 'SeoCmsPage' %} in \<head\>\</head\>.

![default](https://user-images.githubusercontent.com/5114650/52325043-47539400-2a2f-11e9-90e3-c0772c83629e.png)

Then in the CMC in the fields of the CEO add the desired values and they are displayed on the site. It works.

I added {% component 'SeoBlogPost' data = post%} to the blog post page template. In the blog entry, I filled in the SEO fields with the required values, but nothing is displayed on the site (including title tag).

![default](https://user-images.githubusercontent.com/5114650/52325638-7b2fb900-2a31-11e9-85b3-8dfd88d0feaa.png)

![default](https://user-images.githubusercontent.com/5114650/52325236-0ad46800-2a30-11e9-86f3-2e682e9fbb6a.png)

![default](https://user-images.githubusercontent.com/5114650/52325518-fd6bad80-2a30-11e9-943a-f794c79aaf6c.png)

**Comment by Humni** [comment]
Looks like you've missed out just one line, if you add in above the SeoBlogPost Component `{% set post = blogPost.post %}` it should work for you. Let me know if you have any further issues

**Comment by mavsan** [comment]
It does not work, takes data from the blog post, and not the values of the SEO fields.
![default](https://user-images.githubusercontent.com/5114650/52379694-ef607000-2ab6-11e9-9fc5-da56237e38d1.png)

![default](https://user-images.githubusercontent.com/5114650/52379737-0c953e80-2ab7-11e9-97e0-6eacd482e0dc.png)

![default](https://user-images.githubusercontent.com/5114650/52379797-351d3880-2ab7-11e9-8efe-55243e53c663.png)

**Comment by Humni** [comment]
That is by design. If you want to take the SEO fields from the page and _not_ the blog post, then do not include the SeoBlogPost field.

**Comment by mavsan** [comment]
I have now removed the component.

![default](https://user-images.githubusercontent.com/5114650/52380132-56325900-2ab8-11e9-9922-e0c8d4b74149.png)

![default](https://user-images.githubusercontent.com/5114650/52380084-1b302580-2ab8-11e9-8636-b063d4f6662f.png)

**Comment by mavsan** [comment]
Please add a field to add an image to form og: image.

**Comment by Humni** [comment]
@mavsan please open a new issue for requesting new features. This is something that is in the pipeline too
