### ISSUE TITLE
Can I contribute a PR?

### ISSUE THREAD

**Issue by angay9** [suresoftware/october-power-seo#2]
I found one issue with this plugin.

I mentioned it here in the reviews section: 
https://octobercms.com/plugin/suresoftware-powerseo

Can I submit a PR to this repo?

If so, what are the steps ?

And also, I might help you with OG/Twitter tags if that's ok :)

**Comment by Humni** [comment]
Thank you for your review! I'll get onto that issue as soon as I can. PR
format is pretty casual, as long as you clearly articulate your PR and
write code better than mine then it should be good to merge. Always happy
for ideas and input.

Also, please make sure your commits are signed/verified

**Comment by angay9** [comment]
Ok, thanks.

"Also, please make sure your commits are signed/verified" - you mean that I have to have my user and email setup in my git global config?

**Comment by angay9** [comment]
I have the issue that I mentioned fixed, I will send a PR today.

**Comment by Humni** [comment]
This is how you setup signed commits: https://help.github.com/articles/signing-commits/

Sounds great! I look forward to reviewing it

**Comment by Humni** [comment]
@angay9 any update on this? Otherwise, I'll look into adding the `og: image` and twitter fields now too
