### ISSUE TITLE
Dynamic titles are being lost

### ISSUE THREAD

**Issue by RCheesley** [suresoftware/october-power-seo#3]
Hi there,

We seem to have come across an issue with this plugin where we are using custom page titles (in that, they have disappeared!).

There was a thread on this for the original plugin: https://octobercms.com/plugin/support/anandpatel-seoextension/how-to-override-seo-extensions-page-title-seocmspage 

Do you have any recommendations for the best way to proceed?

In our case, it's relating to a forum where the title was dynamically set to be the forum title.

**Comment by Humni** [comment]
What code have you tried for setting it? 

One person on that thread recommended: 

```
function onStart()
{
    $this->layout->components['SeoCmsPage']->seo_title = $dynamicTitle;
}
```

But if this doesn't work I can look into documenting how to do this

**Comment by RCheesley** [comment]
Hi,

Sorry for the delay. This is on the RainLab forum pages - so we're not currently using the Power SEO plugin on those pages (wasn't sure it was supported).

So, unsure how to proceed, would I add the static pages or CMS pages component to the page layout and then add the code you mentioned? Or do I add the code without needing the component on the page?

For context, this impacts circa 6,500 topic pages plus the individual categories, leaving them with a title of 'Forum Topic' or 'Forum Channel' so it's fairly significant!

This is the forum topic page, in case it helps: https://github.com/mautic/website/blob/theme/pages/forum/topic.htm

Thanks for the help!

**Comment by Humni** [comment]
I think the best way forward would be to have another component designed to interact directly with the forum, I'll see what I can do

**Comment by Humni** [comment]
@RCheesley I've for a temporary solution for your page titles. If you add this code to your page it should dynamically set the titles. I've tried to make it as reliable as possible but it hasn't been tested on a large site.

The code is fairly verbose and will add another query to your page, I attempted to get the already loaded channel object from the other component but it was a protected variable and the getChannel method was returning null. 

```php
function onEnd()
{
    if(isset(
          $this->controller, 
          $this->controller->vars, 
          $this->controller->vars['this'], 
          $this->controller->vars['this']['param'], 
          $this->controller->vars['this']['param']['slug']
    )){
        $slug = $this->controller->vars['this']['param']['slug'];
        $channel = RainLab\Forum\Models\Channel::whereSlug($slug)->first();
        if($channel){
            $this->layout->components['SeoCmsPage']->seo_title = $channel->title;
        }
    }
}
```

**Comment by RCheesley** [comment]
Oh, thanks so much!

Do I need to pop the power SEO component on the page for this to work?

I'll test it out and let you know!

Really appreciate the help!
