### ISSUE TITLE
Robots is not populating

### ISSUE THREAD

**Issue by RCheesley** [suresoftware/october-power-seo#4]
Hi there,

I've got this working on our blog posts, but I'm a bit stumped by the robots field which is created, but not populated.

It's doing this:

```<meta name="robots" content=",">```

I've tried changing the settings and saving, using noindex or index, nofollow or follow - still nothing seems to pull through.

The other changes from this plugin are being pushed into the head just fine, so a bit stuck!

**Comment by Humni** [comment]
Very strange, I've been able to replicate this issue so will work on fixing this now. You can expect an update in the next few days to be released with the fix.

**Comment by RCheesley** [comment]
Wonderful, thanks for the speedy reply and look forward to the fix!

**Comment by Humni** [comment]
The issue with the blogPostSEO component has been resolved now, the issue was larger than just the robots so I'm glad you picked this up. Thank you for taking the time to report the issue!
