### ISSUE TITLE
FR: Is it possible to add fields to blog category page?

### ISSUE THREAD

**Issue by RCheesley** [suresoftware/october-power-seo#6]
I'd like to use the category slug (the name of the category) in the title field, if possible!

**Comment by Humni** [comment]
What page are you doing this on? Is it on a page with the blogPost component or is it a blogList component filtered by a category? Need a bit more information before I can help

**Comment by RCheesley** [comment]
Hi there,

So this is on our blog category pages which uses post list as below.

![Screenshot_20190405_100648](https://user-images.githubusercontent.com/2930593/55616827-9d705980-578a-11e9-9c92-8bf43c10951e.png)

**Comment by Humni** [comment]
@RCheesley here is how you can set the page title to the category

```php
function onEnd()
{
    if(isset(
        $this->page->components['blogPosts'],
        $this->page->components['blogPosts']->category,
        $this->page->components['blogPosts']->category->name,
        $this->layout->components['SeoCmsPage']
    )){
        $this->layout->components['SeoCmsPage']->seo_title = $this->page->components['blogPosts']->category->name;
    }
}
```
