### ISSUE TITLE
Unable to get plugin to fire

### ISSUE THREAD

**Issue by RCheesley** [suresoftware/october-power-seo#7]
Hi guys,

I think I have followed the instructions for setup but I just can't get the plugin to fire properly.

Here's what I've done:

1. Install plugin (updated to latest version) & ensure it's enabled
2. Configure settings in back-end per screenshot below
![Screenshot_20190405_100843](https://user-images.githubusercontent.com/2930593/55617561-49ff0b00-578c-11e9-80d3-ba8d816c6dff.png)
3. Place SEO CMS Page component on layout we use for blog posts, and add the code within the head section
![Screenshot_20190405_101710](https://user-images.githubusercontent.com/2930593/55617584-55eacd00-578c-11e9-8bc1-c8a58bf4272c.png)
4. Add SEO Blog Post component to the page for the blog posts, and add the code to the page layout after the blog post component
![Screenshot_20190405_101620](https://user-images.githubusercontent.com/2930593/55617688-98aca500-578c-11e9-8e2a-ae142a898095.png)
5. Add metadata to the blog post
![Screenshot_20190405_101121](https://user-images.githubusercontent.com/2930593/55617729-a95d1b00-578c-11e9-9cde-fd9054d4e9a0.png)

The issues I am finding:

1) No change in browser title
![Screenshot_20190405_100924](https://user-images.githubusercontent.com/2930593/55617765-bed24500-578c-11e9-84e1-a8b3240da698.png)
2) No metadata being pulled through
![Screenshot_20190405_102322](https://user-images.githubusercontent.com/2930593/55617838-e9240280-578c-11e9-88b1-a9010fae55c1.png)

I had this working at some point for the blogs (it works on the other pages) and I'm struggling to figure out what the heck happened/why it isn't working now!

I wondered if it's an issue with the layout having the SEO CMS Page component rather than blog post, but that layout is also used on other non-blog pages. I'm unclear what the difference is?

**Comment by Humni** [comment]
Thank you for the in-depth bug report, I'll set up a local site and see if I can replicate your issue

**Comment by Humni** [comment]
I've had a go at replicating this and unfortunately was not able to replicate the issue. One possibility is that another plugin you have installed is conflicting with it, but I was not able to find all the plugins that you have active on the blog page. Can you provide a full list of the plugins?

**Comment by mskraban** [comment]
I had the same problem, putting tags manually fixed problem for me.
Try to put this inside `<head>` section on your blog layout.
  ```
  <title>{{ post.powerseo_title | generateTitle}}</title>
    <meta name="keywords" content="{{post.powerseo_keywords}}">
    <meta name="description" content="{{post.powerseo_description}}">
    <meta name="robots" content="{{post.powerseo_robot_index}},{{post.powerseo_robot_follow}}">
```

**Comment by RCheesley** [comment]
Hey @mskraban thanks for chiming in!

I don't believe I had seen the instructions to add these anywhere, so that might well help!

Where did you add them, on the layout?

**Comment by RCheesley** [comment]
Awesome, this has fixed the problem for me ... I wonder why it isn't automatically populating though! @Humni maybe something to dig into?

**Comment by Humni** [comment]
In the component, it checks if there is a blog post or a standard CMS page for the meta tags. If both are there then it should use the blog post CMS fields, and not the CMS page fields. I tried quite a few different combos to replicate the issue but it was working every time, so that leaves me thinking it is an interaction with another plugin which is causing the issue. 

Could you both provide a list of the plugins you are using? @RCheesley @mskraban

**Comment by mskraban** [comment]
Plugins:
- Pages
- Backend Plus
- SiteSearch
- Blog
- Power SEO

I also had anand-patel SEO Extension installed.

**Comment by RCheesley** [comment]
Hi there,

Plugins below:

* RainLab Blog
* RainLab Forum
* User Profile
* RainLab Translate (not currently active)
* Debug bar
* Breadcrumbs
* Google Domain Verification
* PowerSEO (also previously had anand-patel SEO extension installed)
* Most Visited
* Comments
* TXT
* Utopigs Sitemap/SEO

Plus a bunch of custom ones.

**Comment by erwanregnier** [comment]
Hi!
I think I have the same issue: the plugin works on  CMS and Static pages but not on Blog pages (no meta added, no title). If i insert the tags manually as @mskraban solution, it works.

Here the plugins I have:
![image](https://user-images.githubusercontent.com/2189069/57702527-93315d00-765e-11e9-9384-a3e9de91e2d9.png)

**Comment by Humni** [comment]
I've not been able to replicate this issue sorry. If you are able to diagnose it more on your end and provide any more information that would be helpful
